trigger:
  - main

pr:
  - main

pool:
  vmImage: "ubuntu-latest"

variables:
  - group: deploy_token_fleksibel
  - name: nodeVersion
    value: "20.x"
  - name: SONARQUBE_SERVICE_CONNECTION
    value: "azurevm"
  - name: SONARQUBE_PROJECT_KEY
    value: "mole-and-hole"
  - name: SONARQUBE_PROJECT_NAME
    value: "mole and hole"

stages:
  # STAGE 1: Build, Test, and Analyze
  - stage: Build_Test_Analyze
    displayName: "1. Build - Test, and Analyze"
    jobs:
      - job: BuildJob
        displayName: "Install, Lint, Analyze, and E2E Test"
        steps:
          # Step 1: Install Node.js
          - task: NodeTool@0
            inputs:
              versionSpec: $(nodeVersion)
            displayName: "Install Node.js $(nodeVersion)"

          # Step 2: Install Dependencies
          - script: npm ci
            displayName: "Clean install project dependencies (npm ci)"

          # Step 3: Instrumentasi kode untuk coverage
          - script: npx nyc instrument ./ ./instrumented
            displayName: "Instrument source code for coverage"

          # Step 4: Copy semua asset pendukung ke instrumented/
          - script: |
              cp index.html instrumented/
              cp style.css instrumented/
              cp script.js instrumented/
              cp package.json instrumented/
              cp -r img instrumented/
              cp -r sounds instrumented/
              cp hammer-hit.png instrumented/
              cp hammer.png instrumented/
              cp README.md instrumented/
            displayName: "Copy all supporting assets to instrumented/"

          # Step 5: Fix Permissions (Prevent Permission Denied)
          - script: chmod -R +x ./node_modules/.bin
            displayName: "Fix permission for node_modules/.bin"
            condition: succeeded()

          # Step 6: Run ESLint & Stylelint
          - script: npm run lint
            displayName: 'Run Linter (ESLint & Stylelint)'
            continueOnError: true

          # Step 7: Prepare SonarQube Analysis
          - task: SonarQubePrepare@7
            inputs:
              SonarQube: $(SONARQUBE_SERVICE_CONNECTION)
              scannerMode: "CLI"
              configMode: "manual"
              cliProjectKey: $(SONARQUBE_PROJECT_KEY)
              cliProjectName: $(SONARQUBE_PROJECT_NAME)
              extraProperties: |
                sonar.sources=.
                sonar.exclusions=**/node_modules/**,cypress/**
                sonar.javascript.lcov.reportPaths=coverage/lcov.info
            displayName: "Prepare SonarQube Analysis Configuration"

          - task: SonarQubeAnalyze@7
            displayName: "Run SonarQube Analysis"

          - task: SonarQubePublish@7
            displayName: "Publish SonarQube Quality Gate Result"

          # Step 8: Jalankan HTTP Server dari dalam folder instrumented/
          - script: npx http-server -p 8080 &
            displayName: "Start HTTP Server for Cypress (Port 8080) in instrumented/"
            workingDirectory: $(System.DefaultWorkingDirectory)/instrumented

          # Step 9: Jalankan Cypress test dari folder instrumented/
          - script: npx cypress run --spec "../cypress/e2e/mole_and_hole.cy.js"
            displayName: "Run Cypress E2E Tests (on instrumented/)"
            workingDirectory: $(System.DefaultWorkingDirectory)/instrumented
            env:
              CYPRESS_BASE_URL: "http://localhost:8080"
            continueOnError: true

          # Step 10: Publish code coverage artifact
          - task: PublishBuildArtifacts@1
            inputs:
              PathtoPublish: 'coverage'
              ArtifactName: 'CodeCoverage'
              publishLocation: 'Container'
            displayName: 'Publish Code Coverage Artifact'

          # Step 11: Publish Cypress Test Results
          - task: PublishTestResults@2
            inputs:
              testResultsFormat: "JUnit"
              testResultsFiles: "**/results/cypress-results-*.xml"
              mergeTestResults: true
              failTaskOnFailedTests: true
            displayName: "Publish Cypress Test Results"
            condition: succeededOrFailed()

  # STAGE 2: Staging - Prepare Artifact
  - stage: Staging
    displayName: "2. Staging - Prepare Deploy Artifact"
    dependsOn: Build_Test_Analyze
    condition: succeeded()
    jobs:
      - job: StagingJob
        displayName: "Create Release Artifact"
        steps:
          - checkout: self
            displayName: "Checkout source code"

          # Copy Game Files to Staging Directory
          - task: CopyFiles@2
            inputs:
              SourceFolder: "$(Build.SourcesDirectory)"
              Contents: |
                index.html
                style.css
                script.js
                img/**
                sounds/**
                hammer-hit.png
                hammer.png
                README.md
              TargetFolder: "$(Build.ArtifactStagingDirectory)/game-files"
            displayName: "Copy game files to Staging Directory"

          - task: PublishBuildArtifacts@1
            inputs:
              PathtoPublish: "$(Build.ArtifactStagingDirectory)/game-files"
              ArtifactName: "HoleAndMoleGameDrop"
              publishLocation: "Container"
            displayName: "Publish Game Artifact (HoleAndMoleGameDrop)"

  # STAGE 3: Deploy - Deploy to Azure Static Web App
  - stage: Deploy_Static_Web_App
    displayName: "3. Deploy - Deploy to Azure Static Web App"
    dependsOn: Staging
    condition: succeeded()
    jobs:
      - job: DeployJob
        displayName: "Deploy Game to Azure Static Web App"
        steps:
          - task: DownloadBuildArtifacts@0
            inputs:
              buildType: current
              artifactName: HoleAndMoleGameDrop
              downloadPath: $(System.ArtifactsDirectory)

          - task: AzureStaticWebApp@0
            inputs:
              app_location: ""
              api_location: ""
              output_location: ""
              azure_static_web_apps_api_token: "$(AZURE_STATIC_WEB_APPS_API_TOKEN)"
              skip_app_build: true
              workingDirectory: $(System.ArtifactsDirectory)/HoleAndMoleGameDrop
            displayName: "🚀 Deploy to Azure Static Web App"
